### ISSUE TITLE
That's really really is a hack way

### ISSUE THREAD

**Issue by TangMonk** [matomesc/mongoose-random#4]
I have read you source code. 
I think return query object will better than return result directly, So I can do :

``` javascript
Song.findRandom().limit(10)
```

**Comment by TangMonk** [comment]
When I change your code to:

``` javascript
schema.statics.findRandom = function (query, callback) {
      var self = this;
      var coords = [randFn(), randFn()];

      if (typeof query === 'function') {
        callback = query;
        query = {};
      }

      query[path] = query[path] || {
        $near: {
          $geometry: { type: 'Point', coordinates: coords }
        }
      };

      return self.find(query); // notice here
    };
```

The I try to run: 

``` javascript
Tag.findRandom().exec(function(err, tag){
    console.log(err)
})
```

but throw me an error:

``` javascript
query['random'] = query['random'] || {
                             ^
TypeError: Cannot read property 'random' of undefined
```

**Comment by matomesc** [comment]
Will push fix soon thanks!

**Comment by matomesc** [comment]
@TangMonk check out my [fix](https://github.com/matomesc/mongoose-random/commit/be60efaed251967a6f2194e8873de8727b4ad4f9#diff-168726dbe96b3ce427e7fedce31bb0bcR31) and let me know what you think. We get a `Query` object back from `findRandom`, so you can do the usual `.limit`, `.sort` etc.
